Ask people to list non-consensus dependencies in their explainers.
w3ctag/tag.w3.org pull request #40
Opened 2023-07-14 17:12 UTC by jyasskin

Both @hober and @torgo have complained about Chromium shipping features that depend on other non-consensus features. While Chromium's likely to keep doing this, we can pretty easily list the non-consensus dependencies in the explainer so that y'all don't have to re-discover them. The other benefit of listing these is that it could prompt us to find solutions that don't have as many dependencies, but I couldn't find a place in this repository to cleanly fit in that explanation. Suggestions are welcome.

2023-07-14 18:55 UTC, hober requested changes

2023-07-14 18:55 UTC, hober commented on explainers/template.md
> +multiple browser engines or adopted by a standards working group, list them here.]
Lots of people new to the standards world might think an incubation venue like WICG counts as "a standards working group"; it may be worth clarifying that here.

2023-07-14 21:44 UTC, jyasskin commented on explainers/template.md
> +multiple browser engines or adopted by a standards working group, list them here.]
Sure, what text do you think would be effective?

2023-07-15 01:31 UTC, cynthia commented on explainers/template.md
> +## Non-consensus dependencies
I might suggest something like "work-in-progress" instead of non-consensus. Another common pattern is that other implementations simply don't seem interested enough to provide a position.

2023-07-15 02:02 UTC, jyasskin commented on explainers/template.md
> +## Non-consensus dependencies
I'm happy with whichever wording the TAG prefers. Both options seem to include both "don't have time" and "opposed" dependencies, and I think that's correct.

2023-07-15 15:41 UTC, LeaVerou commented on explainers/template.md
> +## Non-consensus dependencies
Perhaps "Dependencies on non-stable features"? (or "early-stage features"?)

2023-07-17 15:55 UTC, jyasskin commented on explainers/template.md
> +## Non-consensus dependencies
"Non-stable" and "early-stage" aren't great descriptions of some APIs like Web Bluetooth that ought to appear in this list. But I took "Dependencies on non-stable features" anyway.

2023-07-17 15:55 UTC, jyasskin commented on explainers/template.md
> +multiple browser engines or adopted by a standards working group, list them here.]
I added "(that is, not just a W3C community group)".

2024-01-30 18:43 UTC, hober approved these changes
Looks good to me.

2024-01-31 00:59 UTC, martinthomson commented on explainers/template.md
> +## Dependencies on non-stable features
Is it "non-stable" or simply "unstable"?

2024-01-31 01:20 UTC, jyasskin commented on explainers/template.md
> +## Dependencies on non-stable features
See https://github.com/w3ctag/tag.w3.org/pull/40#discussion_r1265573468. I think you'll get more features listed as "non-stable" than "unstable", and even more of you accept "non-consensus".

2024-02-08 01:22 UTC, tantek approved these changes
Yes please

2024-09-03 22:04 UTC, merged